# Generated by Django 2.0.1 on 2018-06-05 20:46

import cloudinary.models
import config.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uccbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('price', config.utils.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Product Price')),
                ('description', models.TextField(max_length=1000, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Product URL')),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[(2, 'Accessories'), (4, 'Bags'), (1, 'Clothing'), (6, 'Denim'), (7, 'Eyewear'), (5, 'Footwear'), (8, 'Intimates'), (3, 'Jewelry'), (10, 'Lifestyle + Objects'), (9, 'Swimwear')], max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Brand Product Image')),
                ('product_gender_type', models.CharField(choices=[('MALE', 'Men'), ('FEMALE', 'Women'), ('UNISEX', 'Unisex')], max_length=100, null=True)),
                ('campaign_type', models.CharField(choices=[('NONE', 'No Campaign'), ('YES', 'Campaign')], max_length=100, null=True)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='selling_categories',
        ),
        migrations.AlterField(
            model_name='creator',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'Accessories'), (4, 'Bags'), (1, 'Clothing'), (6, 'Denim'), (7, 'Eyewear'), (5, 'Footwear'), (8, 'Intimates'), (3, 'Jewelry'), (10, 'Lifestyle + Objects'), (9, 'Swimwear')], max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uccbackend.Brand'),
        ),
    ]
