# Generated by Django 2.0.1 on 2018-06-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
