# Generated by Django 2.0.1 on 2018-06-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel_backend', '0014_auto_20180623_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
