# Generated by Django 2.0.1 on 2018-06-22 02:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel_backend', '0005_auto_20180621_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CON', 'Consulation'), ('COC', 'Content Creation'), ('DES', 'Design'), ('INF', 'Influence'), ('SAL', 'Sales'), ('STR', 'Strategy'), ('TEC', 'Technology')], max_length=100),
        ),
    ]
