# Generated by Django 2.0.1 on 2018-06-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel_backend', '0008_client_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Brand Website'),
        ),
    ]
