# Generated by Django 2.0.1 on 2018-06-25 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel_backend', '0015_auto_20180623_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='unlabel_backend.Client', verbose_name='Client'),
        ),
    ]
