# Generated by Django 2.0.1 on 2018-06-25 04:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel_backend', '0016_auto_20180625_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CON', 'Consultation'), ('COC', 'Content Creation'), ('DES', 'Design'), ('INF', 'Influence'), ('SAL', 'Sales'), ('STR', 'Strategy'), ('TEC', 'Technology')], max_length=100),
        ),
    ]
