# Generated by Django 2.0.1 on 2018-06-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel_backend', '0017_auto_20180625_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
